### PR TITLE
City specific data

### PR DESCRIPTION
**Pull request by jdewasseige**
[work in progress] not to merge yet, just trying out Wikidata queries format

### CODE REVIEW

**Comment by jdewasseige** [comment]
@kristiankyvik

**Comment by jdewasseige** [comment]
ready to merge

**Comment by kristiankyvik** [comment]
awesome will look over tonight!

**Comment by kristiankyvik** [comment]
hei @jdewasseige, would it be possible to transfer this work to a branch in this repo? So I can check it out locally?

**Pull request merged**
